// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKKFzY7Qhdlaqr3HjGa0Rm1E15XgawyHQ',
    appId: '1:154637700596:web:95b05f518f4cc63fcefda1',
    messagingSenderId: '154637700596',
    projectId: 'instagram-ce2c7',
    authDomain: 'instagram-ce2c7.firebaseapp.com',
    storageBucket: 'instagram-ce2c7.firebasestorage.app',
    measurementId: 'G-TVXCJZFZT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm-I_M8WfQFuArEN3E5MyBKs_5RKmQxz8',
    appId: '1:154637700596:android:b7df6463134b54facefda1',
    messagingSenderId: '154637700596',
    projectId: 'instagram-ce2c7',
    storageBucket: 'instagram-ce2c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYmtEvUp4Zacj0G0-vhizJ0odxU_N3kBo',
    appId: '1:154637700596:ios:e432f4b2978d08dccefda1',
    messagingSenderId: '154637700596',
    projectId: 'instagram-ce2c7',
    storageBucket: 'instagram-ce2c7.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );
}
